name: iOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2.0' # Specify the Xcode version

      - name: Install dependencies
        run: |
          sudo xcode-select -s /Applications/Xcode_15.2.0.app/Contents/Developer
          sudo xcodebuild -license accept

      - name: Build
        run: |
          xcodebuild -project CicdSampleApp.xcodeproj \
                      -scheme CicdSampleApp \
                      -sdk iphonesimulator \
                      -destination 'platform=iOS Simulator,name=iPhone 15' \
                      clean build
